version: '3.2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-sudt-faucet-aggron
    restart: always
    env_file:
      - .env.aggron
    ports:
      - '3306:3336'
    networks:
      - sudt_faucet_network
    volumes:
      - mysql-sudt-faucet-aggron:/var/lib/mysql

  issuer-server:
    image: issuer-server
    container_name: sudt-faucet-issuer-server
    restart: always
    env_file:
      - .env.aggron
    ports:
      - '1570:1570'
    networks:
      - sudt_faucet_network
    volumes:
      - issuer-server-log-aggron:/app/packages/app-server-issuer/logs
    depends_on:
      - mysql

  issuer-ui:
    image: issuer-ui
    container_name: sudt-faucet-issuer-ui
    restart: always
    ports:
      - "1080:1080"
    networks:
      - sudt_faucet_network
    depends_on:
      - issuer-server

  claim-ui:
    image: claim-ui
    container_name: sudt-faucet-claim-ui
    restart: always
    ports:
      - "1081:1081"
    networks:
      - sudt_faucet_network
    depends_on:
      - issuer-server

networks:
  sudt_faucet_network:
    driver: bridge

volumes:
  mysql-sudt-faucet-aggron:
  issuer-server-log-aggron:
