version: '3.2'

services:
  mysql:
    container_name: mysql-sudt-faucet-lina
    env_file:
      - .env.lina
    ports:
      - '3337:3306'
    volumes:
      - mysql-sudt-faucet-lina:/var/lib/mysql
    networks:
      sudt_faucet_network_lina:
        aliases:
          - mysql-sudt-faucet

  issuer-server:
    container_name: issuer-server-lina
    env_file:
      - .env.lina
    ports:
      - '1571:1570'
    volumes:
      - issuer-server-log-lina:/app/packages/app-server-issuer/logs
    networks:
      sudt_faucet_network_lina:
        aliases:
          - issuer-server

  issuer-ui:
    image: issuer-ui-lina
    container_name: issuer-ui-lina
    networks:
      - sudt_faucet_network_lina
    ports:
      - "3090:1080"

  claim-ui:
    image: claim-ui-lina
    container_name: claim-ui-lina
    networks:
      - sudt_faucet_network_lina
    ports:
      - "3091:1081"

networks:
  sudt_faucet_network_lina:
    driver: bridge

volumes:
  mysql-sudt-faucet-lina:
  issuer-server-log-lina:
