version: '3.2'

services:
  mysql:
    image: mysql:5.7
    hostname: mysql-sudt-faucet
    restart: always

  issuer-server:
    image: issuer-server
    hostname: issuer-server
    restart: always
    depends_on:
      - mysql

  issuer-ui:
    restart: always
    depends_on:
      - issuer-server

  claim-ui:
    restart: always
    depends_on:
      - issuer-server
